spring.application.name=airBnb

#Database postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.datasource.username=postgres
spring.datasource.password=shardpostgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

jwt.secretKey=asfdosdhgoigfi123oijopjopjopjopj

#Payment related
frontend.url=http://localhost:8080